Adds UserList views (homepage, request and matches)
PiotrSurowiec90/RoamMates pull request #4
Opened 2023-12-14 15:45 UTC by SoundMotives

**New Components:**
- UserList 
- UserCard

**Views:**
- Homepage Authenticated page
- Request page 
- Matches page

**Unit Tests:**
- UserList (for home, matches and request case)
- UserCard 

![Screenshot 2023-12-14 at 15 44 38](https://github.com/PiotrSurowiec90/RoamMates/assets/140538900/7d70c371-e1a6-4b6a-98cd-f96cda453e0e)

2023-12-14 16:32 UTC, Ovie-Eharisi-Ayomah requested changes
The classnames for web elements are too generic and will make end to end testing hard. Please include more unique identifiers for your web elements

2023-12-14 16:42 UTC, ayfw commented
An example below
<h1 className="primary-heading">{heading}</h1>

2023-12-15 11:34 UTC, Ovie-Eharisi-Ayomah commented on frontend/src/components/UserCard/UserCard.js
> +        <div onClick={goToUserDetail} className="user-card shadow-effect">
I believe this is where we can add an id to the user card.

2023-12-15 11:37 UTC, Ovie-Eharisi-Ayomah approved these changes

2023-12-15 11:39 UTC, merged